### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by Danebrouwer97** [sarahm16/burger#1]
## Im just going to add an issue here, much easier to chat this way. Stackoverflow complains about excessive commenting on posts.

I honestly can't seem to find an issue in your code.

did you try __dirname.join('/public')?

Also, I would suggest adding a .gitignore so that your repository does not include node_modules.

**Comment by sarahm16** [comment]
Gah I always forget the .gitignore
But I haven't tried that yet, I'll give it a shot now

**Comment by sarahm16** [comment]
Terminal is yelling at me, it says __dirname.join is not a function

**Comment by Danebrouwer97** [comment]
I think that syntax is wrong actually. That was from the other guy trying to help.

You need to import join from path
```
const { join } = require("path");
app.use(express.static(join(__dirname, '/public')));
```
Then your paths' root will be public, so your content should be accessible via `/assets`

**Comment by sarahm16** [comment]
Still no luck. I'll talk to my teacher tomorrow about it and let you know if we figure it out, thanks for your help!

**Comment by Danebrouwer97** [comment]
Pleasure, let me know what solution your teacher comes up with!

 Might pull the repository and see if I can get it working later.
